---
name: cf-warden
director_uuid: 7cd0ee32-d342-4832-ab72-8f73de72e5de

releases:
 - name: cf-release
   version: latest

networks:

- name: compile
  subnets:
  - range: 10.244.0.240/30
    static:
      - 10.244.0.242 - 10.244.0.242
    cloud_properties:
      name: random
  - range: 10.244.0.244/30
    static:
      - 10.244.0.246 - 10.244.0.246
    cloud_properties:
      name: random
  - range: 10.244.0.248/30
    static:
      - 10.244.0.250 - 10.244.0.250
    cloud_properties:
      name: random
  - range: 10.244.0.252/30
    static:
      - 10.244.0.254 - 10.244.0.254
    cloud_properties:
      name: random
- name: default
  subnets:
  - range: 10.244.0.0/30
    reserved:
      - 10.244.0.1
    static:
      - 10.244.0.2
    cloud_properties:
      name: random
  - range: 10.244.0.4/30
    reserved:
      - 10.244.0.5
    static:
      - 10.244.0.6
    cloud_properties:
      name: random
  - range: 10.244.0.8/30
    reserved:
      - 10.244.0.9
    static:
      - 10.244.0.10
    cloud_properties:
      name: random
  - range: 10.244.0.12/30
    reserved:
      - 10.244.0.13
    static:
      - 10.244.0.14
    cloud_properties:
      name: random
  - range: 10.244.0.16/30
    reserved:
      - 10.244.0.17
    static:
      - 10.244.0.18
    cloud_properties:
      name: random
  - range: 10.244.0.20/30
    reserved:
      - 10.244.0.21
    cloud_properties:
      name: random
  - range: 10.244.0.24/30
    reserved:
      - 10.244.0.25
    cloud_properties:
      name: random
  - range: 10.244.0.28/30
    reserved:
      - 10.244.0.29
    cloud_properties:
      name: random
  - range: 10.244.0.100/26
    reserved:
      - 10.244.0.100
    cloud_properties:
      name: random

update:
  canaries: 1
  canary_watch_time: 30000-600000
  update_watch_time: 30000-600000
  max_in_flight: 4
  max_errors: 1

compilation:
  workers: 1
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    cpu: 4

resource_pools:
  - name: medium
    network: default
    size: 5
    stemcell:
      name: bosh-stemcell
      version: latest
    cloud_properties:
      cpu: 4

jobs:
  - name: core
    release: cf-release
    template:
      - nats
      - health_manager_next
      - login
    instances: 1
    resource_pool: medium
    persistent_disk: 4096
    networks:
    - name: default
      static_ips:
      - 10.244.0.2

  - name: back
    release: cf-release
    template:
      - postgres
    instances: 1
    resource_pool: medium
    persistent_disk: 4096
    networks:
    - name: default
      static_ips:
      - 10.244.0.6
    properties:
      db: databases

# need a separate job for uaa due to https://github.com/cloudfoundry/cf-release/issues/104
  - name: uaa
    release: cf-release
    template:
      - uaa
    instances: 1
    resource_pool: medium
    networks:
      - name: default
        static_ips:
        - 10.244.0.10


  - name: api
    release: cf-release
    template:
      - cloud_controller_ng
      - gorouter
    instances: 1
    resource_pool: medium
    persistent_disk: 4096
    networks:
    - name: default
      static_ips:
      - 10.244.0.14
    properties:
      db: databases

  - name: dea
    release: cf-release
    template:
      - dea_next
    instances: 1
    resource_pool: medium
    networks:
      - name: default
        static_ips:
        - 10.244.0.18
    properties:
      disk_quota_enabled: false

properties:
  cf:
    name: cf-warden
    dns: 10.244.0.14.xip.io
    ip_addresses: ["10.244.0.2"]
    core_size: medium
    security_group: cf
    persistent_disk: 4096
    common_password: admin

  domain: 10.244.0.14.xip.io
  system_domain: 10.244.0.14.xip.io
  system_domain_organization: system_domain
  app_domains:
    - 10.244.0.14.xip.io

  networks:
    apps: default
    management: default

  nats:
    address: 10.244.0.2
    port: 4222
    user: nats
    password: admin
    authorization_timeout: 5

  router:
    port: 8081
    status:
      port: 8080
      user: gorouter
      password: admin

  dea: &dea
    max_memory: 4096
    memory_mb: 4084
    memory_overcommit_factor: 4
    disk_mb: 4096
    disk_overcommit_factor: 4
    kernel_network_tuning_enabled: false

  dea_next: *dea

  service_lifecycle:
    serialization_data_server:
    - 10.244.0.2

  serialization_data_server:
    port: 8080
    logging_level: debug
    upload_token: 8f7COGvThwlmulIzAgOHxMXurBrG364k
    upload_timeout: 10

  databases: &databases
    db_scheme: postgres
    address: 10.244.0.6
    port: 5524
    roles:
      - tag: admin
        name: ccadmin
        password: admin
      - tag: admin
        name: uaaadmin
        password: admin
    databases:
      - tag: cc
        name: ccdb
        citext: true
      - tag: uaa
        name: uaadb
        citext: true

  ccdb: &ccdb
    db_scheme: postgres
    address: 10.244.0.6
    port: 5524
    roles:
      - tag: admin
        name: ccadmin
        password: admin
    databases:
      - tag: cc
        name: ccdb
        citext: true

  ccdb_ng: *ccdb

  uaadb: 
    db_scheme: postgresql
    address:  10.244.0.6
    port: 5524
    roles:
      - tag: admin
        name: uaaadmin
        password: admin
    databases:
      - tag: uaa
        name: uaadb
        citext: true

  cc_api_version: v2

  cc: &cc
    logging_level: debug
    external_host: ccng
    srv_api_uri: http://api.10.244.0.14.xip.io
    cc_partition: default
    db_encryption_key: "b963127302433579"
    bootstrap_admin_email: admin@10.244.0.14.xip.io
    bulk_api_password: admin
    uaa_resource_id: cloud_controller
    staging_upload_user: uploaduser
    staging_upload_password: admin
    resource_pool:
      resource_directory_key: cc-resources
      fog_connection:
        provider: Local
        local_root: /var/vcap/store
    packages:
      app_package_directory_key: cc-packages
      fog_connection:
        provider: Local
        local_root: /var/vcap/store
    droplets:
      droplet_directory_key: cc-droplets
      fog_connection:
        provider: Local
        local_root: /var/vcap/store

  ccng: *cc

  login:
    protocol: http
    links:
      home: http://console.10.244.0.14.xip.io
      passwd: http://console.10.244.0.14.xip.io/password_resets/new
      signup: http://console.10.244.0.14.xip.io/register

  uaa:
    url: http://uaa.10.244.0.14.xip.io
    spring_profiles: postgresql
    no_ssl: true
    catalina_opts: -Xmx768m -XX:MaxPermSize=256m
    resource_id: account_manager
    jwt:
      signing_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIICXAIBAAKBgQDHFr+KICms+tuT1OXJwhCUmR2dKVy7psa8xzElSyzqx7oJyfJ1
        JZyOzToj9T5SfTIq396agbHJWVfYphNahvZ/7uMXqHxf+ZH9BL1gk9Y6kCnbM5R6
        0gfwjyW1/dQPjOzn9N394zd2FJoFHwdq9Qs0wBugspULZVNRxq7veq/fzwIDAQAB
        AoGBAJ8dRTQFhIllbHx4GLbpTQsWXJ6w4hZvskJKCLM/o8R4n+0W45pQ1xEiYKdA
        Z/DRcnjltylRImBD8XuLL8iYOQSZXNMb1h3g5/UGbUXLmCgQLOUUlnYt34QOQm+0
        KvUqfMSFBbKMsYBAoQmNdTHBaz3dZa8ON9hh/f5TT8u0OWNRAkEA5opzsIXv+52J
        duc1VGyX3SwlxiE2dStW8wZqGiuLH142n6MKnkLU4ctNLiclw6BZePXFZYIK+AkE
        xQ+k16je5QJBAN0TIKMPWIbbHVr5rkdUqOyezlFFWYOwnMmw/BKa1d3zp54VP/P8
        +5aQ2d4sMoKEOfdWH7UqMe3FszfYFvSu5KMCQFMYeFaaEEP7Jn8rGzfQ5HQd44ek
        lQJqmq6CE2BXbY/i34FuvPcKU70HEEygY6Y9d8J3o6zQ0K9SYNu+pcXt4lkCQA3h
        jJQQe5uEGJTExqed7jllQ0khFJzLMx0K6tj0NeeIzAaGCQz13oo2sCdeGRHO4aDh
        HH6Qlq/6UOV5wP8+GAcCQFgRCcB+hrje8hfEEefHcFpyKH+5g1Eu1k0mLrxK2zd+
        4SlotYRHgPCEubokb2S1zfZDWIXW3HmggnGgM949TlY=
        -----END RSA PRIVATE KEY-----
      verification_key: |
        -----BEGIN PUBLIC KEY-----
        MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDHFr+KICms+tuT1OXJwhCUmR2d
        KVy7psa8xzElSyzqx7oJyfJ1JZyOzToj9T5SfTIq396agbHJWVfYphNahvZ/7uMX
        qHxf+ZH9BL1gk9Y6kCnbM5R60gfwjyW1/dQPjOzn9N394zd2FJoFHwdq9Qs0wBug
        spULZVNRxq7veq/fzwIDAQAB
        -----END PUBLIC KEY-----
    cc:
      client_secret: admin
    admin:
      client_secret: admin
    batch:
      username: batchuser
      password: admin
    client:
      autoapprove:
        - cf
        - vmc
        - my
        - micro
        - support-signon
        - login
    clients:
      login:
        override: true
        scope: openid
        authorities: oauth.login
        secret: admin
        authorized-grant-types: authorization_code,client_credentials,refresh_token
        redirect-uri: http://login.10.244.0.14.xip.io
      support-services:
        scope: scim.write,scim.read,openid,cloud_controller.read,cloud_controller.write
        secret: ssosecretsso
        authorized-grant-types: authorization_code,client_credentials
        redirect-uri: http://support-signon.10.244.0.14.xip.io
        authorities: portal.users.read
        access-token-validity: 1209600
        refresh-token-validity: 1209600
      vmc:
        override: true
        authorized-grant-types: password,implicit
        authorities: uaa.none
        scope: cloud_controller.read,cloud_controller.write,openid,password.write,cloud_controller.admin,scim.read,scim.write
      cf:
        override: true
        authorized-grant-types: password,implicit,refresh_token
        authorities: uaa.none
        scope: cloud_controller.read,cloud_controller.write,openid,password.write,cloud_controller.admin,scim.read,scim.write
      servicesmgmt:
        override: true
        secret: serivcesmgmtsecret
        scope: openid,cloud_controller.read,cloud_controller.write
        authorities: uaa.resource,oauth.service,clients.read,clients.write,clients.secret
        authorized-grant-types: authorization_code,client_credentials,password,implicit
        redirect-uri: http://servicesmgmt.yourdomain.com/auth/cloudfoundry/callback
        autoapprove: true
    scim:
      users:
      - admin|admin|scim.write,scim.read,openid,cloud_controller.admin
      - services|admin|scim.write,scim.read,openid,cloud_controller.admin
